const style = {
  base: {
    display: 'flex',
    flexDirection: 'column',
  },
  button: {
    display: 'flex',
    flexDirection: 'row',
    padding: '6px 12px',
    margin: '10px',
    fontSize: '14px',
    fontWeight: '400',
    justifyContent: 'flex-end',
    textAlign: 'center',
    touchAction: 'manipulation',
    cursor: 'pointer',
    userSelect: 'none',
    border: '1px solid transparent',
    borderRadius: '4px',
  },
  buttonEn: {
    color: 'white',
    backgroundColor: 'green',
    display: 'flex',
    flexDirection: 'row',
    padding: '6px 12px',
    margin: '10px',
    fontSize: '14px',
    fontWeight: '400',
    justifyContent: 'flex-end',
    textAlign: 'center',
    touchAction: 'manipulation',
    cursor: 'pointer',
    userSelect: 'none',
    border: '1px solid transparent',
    borderRadius: '4px',
  },
};

export default style;
