const styleButton = {
  base: {
    display: 'inline-block',
    padding: '6px 12px',
    marginBottom: '0',
    fontSize: '14px',
    fontWeight: '400',
    textAlign: 'center',
    verticalAlign: 'middle',
    touchAction: 'manipulation',
    cursor: 'pointer',
    userSelect: 'none',
    border: '1px solid transparent',
    borderRadius: '4px',
  },
  dis: {
    color: 'grey',
    display: 'inline-block',
    padding: '6px 12px',
    margin: '10px 20px 10px 10px',
    fontSize: '14px',
    fontWeight: '400',
    textAlign: 'center',
    verticalAlign: 'middle',
    touchAction: 'manipulation',
    cursor: 'pointer',
    userSelect: 'none',
    border: '1px solid transparent',
    borderRadius: '4px',
  },
  primary: {
    backgroundColor: 'green',
    textColor: 'white',
  },
};
export default styleButton;
